#pragma once

#define MAX_LINEA 1024
#define MAX_ARGS 64
#define PROMPT_POR_DEFECTO "> "
#define MAX_HISTORIAL 100
#define FICHERO_HISTORIAL "./.lanzador_history"
#define MAX_PROGRAMAS_POR_LINEA 5
#define VARIABLES_TABLA_HASH_TAMANYO 512
#define ALIASES_TABLA_HASH_TAMANYO 512
